# Generated by Django 2.1.1 on 2018-11-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User_Requests.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='storeProduct',
            field=models.ManyToManyField(blank=True, related_name='ProductStore', to='User_Requests.Product'),
        ),
    ]
