# Generated by Django 2.1.1 on 2018-11-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0002_auto_20181120_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
    ]
