# Generated by Django 2.1.1 on 2018-11-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0004_product_stores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='storeProduct',
        ),
        migrations.AddField(
            model_name='store',
            name='storeProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ProductStore', to='User_Requests.Product'),
        ),
    ]
