# Generated by Django 2.1.1 on 2018-11-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0005_auto_20181120_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='storeProduct',
        ),
        migrations.AddField(
            model_name='store',
            name='storeProduct',
            field=models.ManyToManyField(blank=True, related_name='ProductStore', to='User_Requests.Product'),
        ),
    ]
