# Generated by Django 2.1.1 on 2018-11-20 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0007_auto_20181120_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderQuantity',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='orderedProduct',
            field=models.ManyToManyField(blank=True, to='User_Requests.Product'),
        ),
    ]
