# Generated by Django 2.1.1 on 2018-11-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0009_auto_20181120_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderedProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='orderedProduct',
            field=models.ManyToManyField(blank=True, to='User_Requests.Product'),
        ),
    ]
