# Generated by Django 2.1.1 on 2018-11-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0010_auto_20181120_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderedProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='orderedProduct',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
