# Generated by Django 2.1.1 on 2018-11-20 23:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0012_auto_20181120_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderedProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='orderedProduct',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), null=True, size=None), null=True, size=None),
        ),
    ]
