# Generated by Django 2.1.1 on 2018-11-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0016_auto_20181120_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'processing'), ('1', 'outfordelivery'), ('2', 'delivered')], default='0', max_length=1),
        ),
    ]
