# Generated by Django 2.1.1 on 2018-11-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0017_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
