# Generated by Django 2.1.1 on 2018-11-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0019_profile_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'processing'), ('1', 'outforpickup'), ('2', 'outfordelivery'), ('3', 'delivered')], default='0', max_length=1),
        ),
    ]
