# Generated by Django 2.1.1 on 2018-11-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0022_auto_20181124_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='currentCoord',
            field=models.CharField(default='0,0', max_length=10),
        ),
        migrations.AddField(
            model_name='drone',
            name='destinationCoord',
            field=models.CharField(default='0,0', max_length=10),
        ),
        migrations.AddField(
            model_name='drone',
            name='storeCoord',
            field=models.CharField(default='5,5', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='userCoord',
            field=models.CharField(default='0,0', max_length=10),
        ),
    ]
