# Generated by Django 2.1.1 on 2018-11-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0023_auto_20181124_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='store',
        ),
        migrations.AlterField(
            model_name='profile',
            name='userCoord',
            field=models.CharField(default='1,1', max_length=10),
        ),
    ]
