# Generated by Django 2.1.1 on 2018-12-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Requests', '0025_auto_20181128_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='currentCoord',
            field=models.CharField(default='0,0', max_length=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='destinationCoord',
            field=models.CharField(default='0,0', max_length=100),
        ),
        migrations.AlterField(
            model_name='drone',
            name='storeCoord',
            field=models.CharField(default='5,5', max_length=100),
        ),
    ]
