# Generated by Django 2.1.1 on 2018-10-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BuenoApp', '0002_drone_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
